// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myjvnypoqzjhantdhitd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15anZueXBvcXpqaGFudGRoaXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTkzODUsImV4cCI6MjA2MzU5NTM4NX0.nVAheH1S-gVyn-QO0FG8-j7lD3M1RmIcapdWZ3H1LpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);